### ISSUE TITLE
Unthemed icons appear as a white square

### ISSUE THREAD

**Issue by jm355** [MiepHD/cuscon#18]
I'm using kiss launcher, not sure if it's different for other launchers. But other icon packs like arcticons don't have this issue

**Comment by jm355** [comment]
Arcticons: 
![Screenshot_20240210-120635](https://github.com/MiepHD/cuscon/assets/4341884/749aee76-ea9c-4825-8487-6109e6e1915f)

cuscon:
![Screenshot_20240210-120651](https://github.com/MiepHD/cuscon/assets/4341884/b846675c-2505-4372-ad50-ec545d4866f2)

**Comment by MiepHD** [comment]
This apk doesn't include Theme_resources and appmap. Does that fix this issue? (You may need to uninstall the existing one)
https://github.com/MiepHD/cuscon/blob/master/Cuscon-v4012-foss-release.apk

**Comment by jm355** [comment]
No, same problem :(

**Comment by jm355** [comment]
Another difference could be all the "ic_*.xml" files arcticons has?

**Comment by MiepHD** [comment]
It'll be fixed in the next update 4.0.1.3
