### ISSUE TITLE
 Syncthing-Fork icons appear as a sky blue square

### ISSUE THREAD

**Issue by arkhan** [MiepHD/cuscon#19]
Greetings great work.

A consultation is this icon correct?

![image](https://github.com/MiepHD/cuscon/assets/3141865/0ae63649-49a6-4ecb-8d30-af64ded7c151)

Thanks

**Comment by MiepHD** [comment]
No, it's not 😅 I'll fix that.

**Comment by MiepHD** [comment]
Will be included in the update 4.0.1.7
