### ISSUE TITLE
chromebook launcher support

### ISSUE THREAD

**Issue by bhang657** [MiepHD/cuscon#25]
I'm unsure is this belongs here but Id love to be able to use this icon pack on my Chromebook but can't get it to apply.

disregard and delete this if I'm an idiot, as far as I can tell lawnchair etc wont replace the default launcher.

**Comment by MiepHD** [comment]
I think icon packs are not supported on chromebooks. Thanks for your comment. I've removed it from the supported devices on google play but the apk will be still installable on any device. If this changes anytime soon you please reopen this issue
