### ISSUE TITLE
Can't pay for more than 4 icon request

### ISSUE THREAD

**Issue by phanirithvij** [MiepHD/cuscon#31]
For the Play Store version
I get Error. The item you were attempting to purchase could not be found.

For 6,8,10 purchases. Country India.

**Comment by MiepHD** [comment]
That's intended. I don't accept premium requests at rhe time because I can't work on requests currently

**Comment by phanirithvij** [comment]
Oh shoot. I payed for 4 icons and sent a request just now. I could've been more patient.
Please 🥺 do so when you have time.

**Comment by MiepHD** [comment]
Premium request are now possible again

**Comment by phanirithvij** [comment]
Thanks. As I commented I sent one on Jun 8. Hope you can finish it soon, thanks.

**Comment by MiepHD** [comment]
They should have been added in [v4.0.3.1](https://github.com/MiepHD/cuscon/releases/tag/v4.0.3.1)

**Comment by phanirithvij** [comment]
I saw them just now, thanks!
