### ISSUE TITLE
Icon sumbission for 5 apps

### ISSUE THREAD

**Issue by Gnorv** [MiepHD/cuscon#38]
Hello, thank you for creating this icon pack. I'd like to contribute a few pictures. Since I am not sure what format you need them in I will upload them as SVG and PNG. If another format is better, please tell me.

I made 5 icons, [Umweltbank](#UmweltBank), [Synchronized Tally](#synctally), [SchildiChat Next](#schildi), [Ostrom](#ostrom) and [MeinHeidelberg](#hd)

### <a href="#user-content-umweltbank" id="umweltbank"></a> UmweltBank [de.umweltbank.banking.app](https://play.google.com/store/apps/details?id=de.umweltbank.banking.app&hl=en-US) 
PNG
![Cuscon_UmweltBank](https://github.com/user-attachments/assets/2c938d6e-d68b-4ba7-aec9-7de7a62585d3)
SVG
![Cuscon_UmweltBank](https://github.com/user-attachments/assets/5e588dfd-1c5d-40a5-b9eb-220fa4f1fadb)

### <a href="#user-content-synctally" id="synctally"></a> Synchronized Tally [com.rightclick.tally](https://play.google.com/store/apps/details?id=com.rightclick.tally&hl=en-US)
PNG
![Cuscon_SynchronizedTally](https://github.com/user-attachments/assets/8b2fc964-60a4-43c7-a048-33c6cb7e78e4)
SVG
![Cuscon_SynchronizedTally](https://github.com/user-attachments/assets/33677d04-7e66-44ff-ba46-c8ba9be72488)

### <a href="#user-content-schildi" id="schildi"></a> SchildiChat Next [chat.schildi.android](https://schildi.chat/android/next/)
PNG
![Cuscon_Schildichat-Next](https://github.com/user-attachments/assets/3d172af2-f28f-4115-857c-e7a6321f8bab)
SVG
![Cuscon_Schildichat-Next](https://github.com/user-attachments/assets/c153c9a6-ac94-4769-a1ac-a5615b31ad3a)

### <a href="#user-content-ostrom" id="ostrom"></a> Ostrom [com.ostrommobile](https://play.google.com/store/apps/details?id=com.ostrommobile)
PNG
![Cuscon_Ostrom](https://github.com/user-attachments/assets/776a476f-aa98-452a-a85d-4390ad01c632)
SVG
![Cuscon_Ostrom](https://github.com/user-attachments/assets/f4667632-e21d-4106-aa28-a9c9c1316840)

### <a href="#user-content-hd" id="hd"></a> MeinHeidelberg [com.sovanta.cities](https://play.google.com/store/apps/details?id=com.sovanta.cities)
PNG
![Cuscon_Heidelberg](https://github.com/user-attachments/assets/06ff4ee6-69e0-4381-ac61-b32a7751a463)
SVG
![Cuscon_Heidelberg](https://github.com/user-attachments/assets/4269dde8-2c40-4dbf-9f5c-e74a91b6016f)

**Comment by MiepHD** [comment]
Thanks for your contribution. The icons will be included in the next release (4039).

**Comment by Gnorv** [comment]
Could you give some feedback about my submission process? Is it good, can I optimise something?

**Comment by MiepHD** [comment]
It's good. 👍 Submittig the images as png is enough. If you want you could try to follow the instructions on how to create a pull request with your icons. If you don't want to do that it'd be helpful if you'd create a request to yourself and send along the xml files of that request.
