### ISSUE TITLE
Adding to F-Droid

### ISSUE THREAD

**Issue by RedSteel-1** [MiepHD/cuscon#5]
Would be cool to see it available in F-Droid.

This would also provide automatic updates, instead of having to manually download the APK from github

**Comment by MiepHD** [comment]
I'm already trying this but not sure if it'll work. In the meantime you can try Aurora-Store
Gitlab Issue: https://gitlab.com/fdroid/rfp/-/issues/2303
Aurora-Store: https://auroraoss.com/

**Comment by Donnnno** [comment]
Hey! Just change this line in your [build gradle](https://github.com/MiepHD/cuscon/blob/master/app/build.gradle):

`dependencies { implementation 'com.github.zixpo:candybar:3.17.1' `

to this

`dependencies { implementation 'com.github.donnnno:candybar-foss:3.17.4'`

That'll do the trick!

**Comment by Donnnno** [comment]
Oh, and you can also create two different builds, like Delta does (Play & FOSS):

https://github.com/Delta-Icons/android/blob/master/app/build.gradle

**Comment by Cyanide-1** [comment]
I hope this gets added to fdroid.

**Comment by MiepHD** [comment]
It's merged. May take a while to appear in the store
https://gitlab.com/fdroid/fdroiddata/-/commit/ac45b1cbedb0a5a42916ee457af6109c6b3c96af
